<?php

return $cidades = ['Albergaria-a-Velha',
'Aljustrel',
'Almodôvar',
'Alvito',
'Anadia',
'Arouca',
'Aveiro',
'Barrancos',
'Beja',
'Castelo de Paiva',
'Castro Verde',
'Cuba',
'Espinho',
'Estarreja',
'Ferreira do Alentejo',
'Mealhada',
'Moura',
'Murtosa',
'Mértola',
'Odemira',
'Oliveira de Azeméis',
'Oliveira do Bairro',
'Ourique',
'Ovar',
'Santa Maria da Feira',
'Serpa',
'Sever do Vouga',
'São João da Madeira',
'Vagos',
'Vale de Cambra',
'Vidigueira',
'Águeda',
'Ílhavo',
'Abrantes',
'Aguiar da Beira',
'Alandroal',
'Albufeira',
'Alcanena',
'Alcobaça',
'Alcochete',
'Alcoutim',
'Alcácer do Sal',
'Alenquer',
'Alfândega da Fé',
'Alijó',
'Aljezur',
'Almada',
'Almeida',
'Almeirim',
'Alpiarça',
'Alter do Chão',
'Alvaiázere',
'Amadora',
'Amarante',
'Amares',
'Angra do Heroísmo',
'Ansião',
'Arcos de Valdevez',
'Arganil',
'Armamar',
'Arraiolos',
'Arronches',
'Arruda dos Vinhos',
'Avis',
'Azambuja',
'Baião',
'Barcelos',
'Barreiro',
'Batalha',
'Belmonte',
'Benavente',
'Bombarral',
'Borba',
'Boticas',
'Braga',
'Bragança',
'Cabeceiras de Basto',
'Cadaval',
'Caldas da Rainha',
'Calheta (Madeira)',
'Calheta (São Jorge)',
'Caminha',
'Campo Maior',
'Cantanhede',
'Carrazeda de Ansiães',
'Carregal do Sal',
'Cartaxo',
'Cascais',
'Castanheira de Pêra',
'Castelo Branco',
'Castelo de Vide',
'Castro Daire',
'Castro Marim',
'Celorico da Beira',
'Celorico de Basto',
'Chamusca',
'Chaves',
'Cinfães',
'Coimbra',
'Condeixa-a-Nova',
'Constância',
'Coruche',
'Corvo',
'Covilhã',
'Crato',
'Câmara de Lobos',
'Elvas',
'Entroncamento',
'Esposende',
'Estremoz',
'Fafe',
'Faro',
'Felgueiras',
'Ferreira do Zêzere',
'Figueira da Foz',
'Figueira de Castelo Rodrigo',
'Figueiró dos Vinhos',
'Fornos de Algodres',
'Freixo de Espada à Cinta',
'Fronteira',
'Funchal',
'Fundão',
'Gavião',
'Golegã',
'Gondomar',
'Gouveia',
'Grândola',
'Guarda',
'Guimarães',
'Góis',
'Horta',
'Idanha-a-Nova',
'Lagoa (Algarve)',
'Lagoa (São Miguel)',
'Lagos',
'Lajes das Flores',
'Lajes do Pico',
'Lamego',
'Leiria',
'Lisboa',
'Loulé',
'Loures',
'Lourinhã',
'Lousada',
'Lousã',
'Macedo de Cavaleiros',
'Machico',
'Madalena',
'Mafra',
'Maia',
'Mangualde',
'Manteigas',
'Marco de Canaveses',
'Marinha Grande',
'Marvão',
'Matosinhos',
'Mação',
'Meda',
'Melgaço',
'Mesão Frio',
'Mira',
'Miranda do Corvo',
'Miranda do Douro',
'Mirandela',
'Mogadouro',
'Moimenta da Beira',
'Moita',
'Monchique',
'Mondim de Basto',
'Monforte',
'Montalegre',
'Montemor-o-Novo',
'Montemor-o-Velho',
'Montijo',
'Monção',
'Mora',
'Mortágua',
'Mourão',
'Murça',
'Nazaré',
'Nelas',
'Nisa',
'Nordeste',
'Odivelas',
'Oeiras',
'Oleiros',
'Olhão',
'Oliveira de Frades',
'Oliveira do Hospital',
'Ourém',
'Palmela',
'Pampilhosa da Serra',
'Paredes',
'Paredes de Coura',
'Paços de Ferreira',
'Pedrógão Grande',
'Penacova',
'Penafiel',
'Penalva do Castelo',
'Penamacor',
'Penedono',
'Penela',
'Peniche',
'Peso da Régua',
'Pinhel',
'Pombal',
'Ponta Delgada',
'Ponta do Sol',
'Ponte da Barca',
'Ponte de Lima',
'Ponte de Sor',
'Portalegre',
'Portel',
'Portimão',
'Porto',
'Porto de Mós',
'Porto Moniz',
'Porto Santo',
'Povoação',
'Praia da Vitória',
'Proença-a-Nova',
'Póvoa de Lanhoso',
'Póvoa de Varzim',
'Redondo',
'Reguengos de Monsaraz',
'Resende',
'Ribeira Brava',
'Ribeira de Pena',
'Ribeira Grande',
'Rio Maior',
'Sabrosa',
'Sabugal',
'Salvaterra de Magos',
'Santa Comba Dão',
'Santa Cruz',
'Santa Cruz da Graciosa',
'Santa Cruz das Flores',
'Santa Marta de Penaguião',
'Santana',
'Santarém',
'Santiago do Cacém',
'Santo Tirso',
'Sardoal',
'Seia',
'Seixal',
'Sernancelhe',
'Sertã',
'Sesimbra',
'Setúbal',
'Silves',
'Sines',
'Sintra',
'Sobral de Monte Agraço',
'Soure',
'Sousel',
'Sátão',
'São Brás de Alportel',
'São João da Pesqueira',
'São Pedro do Sul',
'São Roque do Pico',
'São Vicente',
'Tabuaço',
'Tarouca',
'Tavira',
'Terras de Bouro',
'Tomar',
'Tondela',
'Torre de Moncorvo',
'Torres Novas',
'Torres Vedras',
'Trancoso',
'Trofa',
'Tábua',
'Valença',
'Valongo',
'Valpaços',
'Velas',
'Vendas Novas',
'Viana do Alentejo',
'Viana do Castelo',
'Vieira do Minho',
'Vila de Rei',
'Vila do Bispo',
'Vila do Conde',
'Vila do Porto',
'Vila Flor',
'Vila Franca de Xira',
'Vila Franca do Campo',
'Vila Nova da Barquinha',
'Vila Nova de Cerveira',
'Vila Nova de Famalicão',
'Vila Nova de Foz Côa',
'Vila Nova de Gaia',
'Vila Nova de Paiva',
'Vila Nova de Poiares',
'Vila Pouca de Aguiar',
'Vila Real',
'Vila Real de Santo António',
'Vila Velha de Ródão',
'Vila Verde',
'Vila Viçosa',
'Vimioso',
'Vinhais',
'Viseu',
'Vizela',
'Vouzela',
'Évora',
'Óbidos'];
